# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arrayShift <- function(x, tidx, sidx, shift, dims) {
    .Call(`_dipsaus_arrayShift`, x, tidx, sidx, shift, dims)
}

collapser <- function(x, dims, keep) {
    .Call(`_dipsaus_collapser`, x, dims, keep)
}

