# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arrayShift <- function(x, tidx, sidx, shift, dims) {
    .Call(`_dipsaus_arrayShift`, x, tidx, sidx, shift, dims)
}

baselineArray <- function(x, bl, dims, bldims, tidx, per, rest, method) {
    .Call(`_dipsaus_baselineArray`, x, bl, dims, bldims, tidx, per, rest, method)
}

collapser <- function(x, dims, keep) {
    .Call(`_dipsaus_collapser`, x, dims, keep)
}

pwelch <- function(x, fs, winLen, noverlap, nfft, nthread) {
    .Call(`_dipsaus_pwelch`, x, fs, winLen, noverlap, nfft, nthread)
}

wavelet_kernels <- function(freqs, srate, wave_cycles, nthread) {
    .Call(`_dipsaus_wavelet_kernels`, freqs, srate, wave_cycles, nthread)
}

wavelet <- function(data, freqs, srate, wave_cycles, nthread, demean = TRUE, power = FALSE, phase = FALSE, ampl = FALSE, cplx = TRUE, knel = FALSE, transpose = TRUE) {
    .Call(`_dipsaus_wavelet`, data, freqs, srate, wave_cycles, nthread, demean, power, phase, ampl, cplx, knel, transpose)
}

guard_length <- function(n) {
    .Call(`_dipsaus_guard_length`, n)
}

cosine_gen <- function(n, a, sym) {
    .Call(`_dipsaus_cosine_gen`, n, a, sym)
}

hamming_gen <- function(n, alpha, sym) {
    .Call(`_dipsaus_hamming_gen`, n, alpha, sym)
}

hann <- function(n, sym) {
    .Call(`_dipsaus_hann`, n, sym)
}

hanning <- function(n) {
    .Call(`_dipsaus_hanning`, n)
}

detrend_naive <- function(y, input) {
    .Call(`_dipsaus_detrend_naive`, y, input)
}

fftw_r2c <- function(N, data, retConj, gc) {
    .Call(`_dipsaus_fftw_r2c`, N, data, retConj, gc)
}

test_dipsaus_signals <- function() {
    invisible(.Call(`_dipsaus_test_dipsaus_signals`))
}

